# Generated by Django 5.2.13 on 2026-05-01 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nyiso_report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=500)),
                ('frequency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('real', 'Real Time'), ('HOUR', 'Hourly'), ('DAY', 'Daily'), ('YEAR', 'Yearly')], max_length=20), blank=True, default=list, size=None)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('nyiso_report_id', models.BigAutoField(db_column='nyiso_report_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'energy_hub_nyiso_report',
                'abstract': False,
            },
        ),
    ]
