# Generated by Django 5.2.13 on 2026-05-01 17:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyiso_report',
            name='file_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HTML', 'html'), ('CSV', 'CSV'), ('PDF', 'PDF')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='nyiso_report',
            name='frequency',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('REAL', 'Real Time'), ('HOUR', 'Hourly'), ('DAY', 'Daily'), ('YEAR', 'Yearly')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
