# Generated by Django 5.2.13 on 2026-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0002_nyiso_report_file_type_alter_nyiso_report_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyiso_report',
            name='earliest_report_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='file_name_format',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='latest_report_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='parse_status',
            field=models.CharField(choices=[('OK', 'Parsed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PARTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='source_page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
