# Generated by Django 5.2.13 on 2026-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0003_nyiso_report_earliest_report_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyiso_report',
            name='active_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='task_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='nyiso_report',
            name='task_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
