# Generated by Django 5.2.13 on 2026-05-03 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0004_nyiso_report_active_task_id_nyiso_report_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyiso_report',
            name='frequency',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('REAL', 'Real Time'), ('HOUR', 'Hourly'), ('DAY', 'Daily'), ('YEAR', 'Yearly'), ('SINGLE', 'Singular')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
