# Generated by Django 5.2.13 on 2026-05-03 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0005_alter_nyiso_report_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyiso_report',
            name='file_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HTML', 'html'), ('CSV', 'CSV'), ('PDF', 'PDF'), ('ZIP', 'ZIP')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
