# Generated by Django 5.2.13 on 2026-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0006_alter_nyiso_report_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyiso_report',
            name='content_type',
            field=models.CharField(choices=[('FILE_LIST', 'File List'), ('INLINE_FEED', 'Inline Feed')], default='FILE_LIST', max_length=20),
        ),
    ]
