# Generated by Django 5.2.12 on 2026-05-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metric_parse_run_source_file_schema_mapping_and_more'),
        ('energy_hub', '0007_nyiso_report_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyiso_dimension_entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_kind', models.CharField(choices=[('zone', 'Zone'), ('node', 'Node'), ('interface', 'Interface'), ('hub', 'Trading Hub')], db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geometry_geojson', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('nyiso_dimension_entity_id', models.BigAutoField(db_column='nyiso_dimension_entity_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'energy_hub_nyiso_dimension_entity',
                'indexes': [models.Index(fields=['dimension_kind', 'external_id'], name='energy_hub__dimensi_5d11cc_idx')],
                'unique_together': {('dimension_kind', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='nyiso_metric_alias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nyiso_field_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('nyiso_metric_alias_id', models.BigAutoField(db_column='nyiso_metric_alias_id', primary_key=True, serialize=False)),
                ('nyiso_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_aliases', to='energy_hub.nyiso_report')),
                ('schema_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nyiso_aliases', to='core.schema_mapping')),
            ],
            options={
                'db_table': 'energy_hub_nyiso_metric_alias',
                'indexes': [models.Index(fields=['nyiso_report'], name='energy_hub__nyiso_r_470a11_idx')],
                'unique_together': {('nyiso_report', 'schema_mapping')},
            },
        ),
        migrations.CreateModel(
            name='nyiso_report_file',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nyiso_report_file_id', models.BigAutoField(db_column='nyiso_report_file_id', primary_key=True, serialize=False)),
                ('nyiso_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='energy_hub.nyiso_report')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nyiso_reports', to='core.source_file')),
            ],
            options={
                'db_table': 'energy_hub_nyiso_report_file',
                'indexes': [models.Index(fields=['nyiso_report'], name='energy_hub__nyiso_r_8a59d9_idx'), models.Index(fields=['source_file'], name='energy_hub__source__f5a4a7_idx')],
                'unique_together': {('nyiso_report', 'source_file')},
            },
        ),
        migrations.CreateModel(
            name='nyiso_timeseries_link',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nyiso_timeseries_link_id', models.BigAutoField(db_column='nyiso_timeseries_link_id', primary_key=True, serialize=False)),
                ('nyiso_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_links', to='energy_hub.nyiso_report')),
                ('timeseries_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nyiso_links', to='core.timeseries_point')),
            ],
            options={
                'db_table': 'energy_hub_nyiso_timeseries_link',
                'indexes': [models.Index(fields=['nyiso_report'], name='energy_hub__nyiso_r_bf309a_idx'), models.Index(fields=['timeseries_point'], name='energy_hub__timeser_e62d7e_idx')],
                'unique_together': {('nyiso_report', 'timeseries_point')},
            },
        ),
    ]
