# Generated by Django 5.2.12 on 2026-05-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0008_nyiso_dimension_entity_nyiso_metric_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyiso_report_schedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('METADATA_REFRESH', 'Metadata Refresh'), ('FILE_DOWNLOAD_RANGE', 'File Download Range')], default='METADATA_REFRESH', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=1440)),
                ('use_cache', models.BooleanField(default=True)),
                ('run_async', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rolling_window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('template_values_json', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_state', models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=16)),
                ('last_message', models.TextField(blank=True, default='')),
                ('nyiso_report_schedule_id', models.BigAutoField(db_column='nyiso_report_schedule_id', primary_key=True, serialize=False)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='energy_hub.nyiso_report')),
            ],
            options={
                'db_table': 'energy_hub_nyiso_report_schedule',
            },
        ),
        migrations.CreateModel(
            name='nyiso_schedule_run',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.CharField(default='scheduler', max_length=20)),
                ('state_value', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reports_targeted', models.IntegerField(default=0)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('nyiso_schedule_run_id', models.BigAutoField(db_column='nyiso_schedule_run_id', primary_key=True, serialize=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='energy_hub.nyiso_report_schedule')),
            ],
            options={
                'db_table': 'energy_hub_nyiso_schedule_run',
            },
        ),
        migrations.AddIndex(
            model_name='nyiso_report_schedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='energy_hub__is_acti_aff8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='nyiso_report_schedule',
            index=models.Index(fields=['mode', 'is_active'], name='energy_hub__mode_a1a71c_idx'),
        ),
        migrations.AddIndex(
            model_name='nyiso_schedule_run',
            index=models.Index(fields=['schedule', '-created_at'], name='energy_hub__schedul_f35ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='nyiso_schedule_run',
            index=models.Index(fields=['state_value', '-created_at'], name='energy_hub__state_v_dfa637_idx'),
        ),
    ]
