# Generated by Django 5.2.12 on 2026-05-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0009_nyiso_report_schedule_nyiso_schedule_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyiso_schedule_run',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='nyiso_report_schedule',
        ),
        migrations.DeleteModel(
            name='nyiso_schedule_run',
        ),
    ]
