# Generated by Django 5.2.13 on 2026-05-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_definition_schedule_run'),
        ('energy_hub', '0010_remove_nyiso_schedule_run_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyiso_schedule_definition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.schedule_definition',),
        ),
    ]
