# Generated by Django 5.2.13 on 2026-05-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_column_mapping_unit_type_and_more'),
        ('energy_hub', '0011_nyiso_schedule_definition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nyiso_metric_alias',
            unique_together={('nyiso_report', 'column_mapping')},
        ),
        migrations.AddField(
            model_name='nyiso_metric_alias',
            name='column_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nyiso_aliases', to='core.column_mapping'),
        ),
        migrations.RemoveField(
            model_name='nyiso_metric_alias',
            name='schema_mapping',
        ),
    ]
