# Generated by Django 5.2.13 on 2026-05-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0012_alter_nyiso_metric_alias_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nyiso_metric_alias',
            unique_together={('nyiso_report', 'nyiso_field_name')},
        ),
    ]
