# Generated by Django 5.2.13 on 2026-05-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_hub', '0013_fix_nyiso_metric_alias_unique_field_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nyiso_timeseries_link',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nyiso_timeseries_link',
            name='nyiso_report',
        ),
        migrations.RemoveField(
            model_name='nyiso_timeseries_link',
            name='timeseries_point',
        ),
        migrations.DeleteModel(
            name='nyiso_metric_alias',
        ),
        migrations.DeleteModel(
            name='nyiso_timeseries_link',
        ),
    ]
